[package]
name = "ta-ko-ho/test-repo-delete-me-please"
version = "0.1.1"
description = "wasmer-tests/wasmer-edge-svelte-sample website"
repository = "https://github.com/ta-ko-ho/test-repo-delete-me-please"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "build"
